version: '3'

services:
  redis:
    image: redis:7.0.12
    container_name: portal-redis
    restart: always
    environment: 
      - .env
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
    ports:
      - "6379:6379"

# docker exec -it portal-redis redis-cli